python -m pdb Infer_ans_main.py \
 --data_path ../data/NELL0 \
 --prefix_path ../data/NELL0/processed \
 --rel_width 50 \
 --ent_width 50 \
 --tail_width 5 \
 --normalize_rule softmax \
 --ground_truth_path test_sorted_answers \
 --prediction_path llmR/trainG_testQ_preds \
 --log_score_path llmR/trainG_testQ_scores \
 --random_path llmR/random_list \
 --random_num 100 \
 --quries_file test-queries.pkl \
 --triplets_file llmR/train-headent-triplets.pkl\
 --qtype2cnt_file test-qtype2cnt.pkl \
 --id2q_file test-id2q.pkl \
 --qtype 1p \
 --score_file 1p_withDR.txt \
 --api gpt \
 --model_name gpt-4 \
 --depth 3 \
 --path_width 50 \
 --prompt_width 10 \
 --device cuda:0 \
 --encoder_model bert-base-uncased \
 --ckpt_file ../path_score/output/2024-11-22-19-52/encoder_ep%s.ckpt \
 --ckpt_ep 16 \
 --DR_bsz 64
